-- 1. Create the Roasters table first
CREATE TABLE roasters (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255),
                          location VARCHAR(255),
                          year_established INTEGER,
                          deleted_at TIMESTAMP WITHOUT TIME ZONE
);

-- 2. Create the Coffee Beans table
CREATE TABLE coffee_beans (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name VARCHAR(255),
                              origin VARCHAR(255),
                              roast_level VARCHAR(50), -- Storing Enum as STRING
                              price_per_kg NUMERIC(19, 2), -- Better for currency than FLOAT
                              stock_quantity INTEGER,
                              deleted_at TIMESTAMP WITHOUT TIME ZONE,
                              roaster_id BIGINT,

    -- Foreign Key Constraint
                              CONSTRAINT fk_coffee_bean_roaster
                                  FOREIGN KEY (roaster_id)
                                      REFERENCES roasters(id)
);